# Generated by Django 4.2.26 on 2025-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0003_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the movie was archived. Null if not archived.', null=True),
        ),
    ]
